### ISSUE TITLE
unable to parse turtle file: unexpected token `closing `]``

### ISSUE THREAD

**Issue by clci** [timothee-haudebourg/turtle-syntax#1]
I ran the provided example `simple.rs` against some of the LV2 audio plugin description files, for example [this one](https://github.com/x42/xfade.lv2/blob/49cceb934883a3bde8d1f495b77f4c4b9084bf7f/xfade.ttl.in) :+1: 

```
error: parse error: unexpected token `closing `]``
   ┌─ /usr/lib/lv2/xfade.lv2/xfade.ttl:70:3
   │
70 │         ] , [
   │         ^
```

Are these files written using a grammar still not supported by `turtle-syntax` or they are out of the ttl file format specifications?

**Comment by timothee-haudebourg** [comment]
Hi @clci sorry for the delay I don't have much time. There is indeed an issue with [rule 7 of the Turtle grammar](https://www.w3.org/TR/turtle/#sec-grammar):
```
[7] | predicateObjectList | ::= | verb objectList (';' (verb objectList)?)*
```
which I misinterpreted as 
```
[7] | predicateObjectList | ::= | verb objectList (';' verb objectList)*
```
so the parser was expecting some verb after the `;` line 69. Let me fix this real quick.

**Comment by timothee-haudebourg** [comment]
Please upgrade to version 5.0.3 to see the fix.
